language: scala

before_script:
  - cd foo

script:
  - sbt clean coverage test

after_success:
  - sbt coverageReport coveralls

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
